CREATE DATABASE ConnectPlus;
GO

CREATE DATABASE ConnectPlus;
GO

USE ConnectPlus;
GO

CREATE TABLE TipoContato (
    IdTipoContato UNIQUEIDENTIFIER PRIMARY KEY DEFAULT ((NEWID())),
    Titulo VARCHAR(100) NOT NULL
);
GO

CREATE TABLE Contato (
    IdContato UNIQUEIDENTIFIER PRIMARY KEY DEFAULT((NEWID())),
    Nome VARCHAR(150) NOT NULL,
    FormaContato VARCHAR(150) NOT NULL,
    Imagem VARCHAR(100) NOT NULL,
    IdTipoContato UNIQUEIDENTIFIER FOREIGN KEY REFERENCES TipoContato(IdTipoContato)
        
);
GO